version: '3.4'

services:
  webapi:
    container_name: c_webapi
    ports:
      - "5000:8080"
    depends_on:
      - db
    env_file:
      - ./server/.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=peakeye1!
      - DB_NAME=PeakEyeCaseDb
      - JWT_SECRET_KEY=top_secret_key_for_jwt_top_secret_key_for_jwt
      - JWT_EXPIRATION_TIME=3600 # as seconds

  webapp:
    container_name: c_webapp
    ports:
      - "3000:3000"

  db:
    container_name: c_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: peakeye1!
      POSTGRES_DB: PeakEyeCaseDb
    ports:
      - "5454:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
