name: Grype

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.4.0

      - name: Build and Run with Docker Compose
        run:  docker-compose -p peakeye up -d

      - name: Install Grype
        run: curl -sfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Grype Scans
        run: |
          grype webapp -o json > webapp.report.json &&

      - name: Upload Grype Reports
        uses: actions/upload-artifact@v4.3.4
        with:
          name: reports
          path: |
            webapp.report.json
